### ISSUE TITLE
Working API

### ISSUE THREAD

**Issue by rajitbansal** [MrLuit/Luitdev#7]
Do you have a whatsapp api which is currently working?

**Comment by Yakultie** [comment]
He seems to have one, however I don't understand the language so I don't know how to set it up.

**Comment by Yakultie** [comment]
I tried running the php file with no luck.

**Comment by MrLuit** [comment]
Yeah, but this is only the parser of the incoming messages. The actual whatsapp-api is [yowsup](https://github.com/tgalal/yowsup). Go check it out, it's written in Python.
